version: "3.9"

services:
  dj:
    command: /scripts/prod.sh
    expose:
      - ${DJANGO_PORT}
    environment:
      DJANGO_DEBUG: '0'

  nginx:
    image: nginx:1.21.5-alpine
    working_dir: /app
    ports:
      - ${DJANGO_PORT}:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/app:/app
      - ./docker/nginx/logs:/var/log/nginx
      - ./proj/djstatic:/var/djstatic
      - ./proj/djmedia:/var/djmedia
    depends_on:
      - dj
