version: "3.9"

services:
  dj:
    command: /scripts/prod.sh
    expose:
      - ${DJANGO_PORT}
    environment:
      DJANGO_DEBUG: '0'

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - ${DJANGO_PORT}:80
    env_file:
      - ./.env
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./docker/nginx/app:/app
      - ./docker/nginx/logs:/var/log/nginx
      - ./proj/djstatic:/var/djstatic
      - ./proj/djmedia:/var/djmedia
    depends_on:
      - dj
