version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - ./docker/pgdb/conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/pgdb/data:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    env_file:
      - ./.env
    expose:
      - ${REDIS_PORT}
    volumes:
      - ./docker/redis/data:/data
      - ./docker/redis/conf:/usr/local/etc/redis

  rabbitmq:
    image: rabbitmq:3.9.12-management-alpine
    env_file:
      - ./.env
    expose:
      - ${RABBITMQ_PORT}
      - ${RABBITMQ_MANAGE_PORT}
    volumes:
      - ./docker/rabbitmq/data:/var/lib/rabbitmq
      - ./docker/rabbitmq/conf:/etc/rabbitmq/

  dj:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./proj:/proj
      - ./docker/celery/pids:/var/run/celery
      - ./docker/celery/logs:/var/log/celery
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - rabbitmq
