version: "3.9"

services:
  db:
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  redis:
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  rabbitmq:
    ports:
      - ${RABBITMQ_MANAGE_PORT}:${RABBITMQ_MANAGE_PORT}

  dj:
    command: /scripts/dev.sh
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    environment:
      DJANGO_DEBUG: '1'
