# Generated by Django 4.0.1 on 2022-01-11 08:32

import base.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=base.models.my_upload_to, verbose_name='文件')),
                ('img', models.ImageField(blank=True, height_field='image_height', null=True, upload_to=base.models.my_upload_to, verbose_name='图片', width_field='image_width')),
                ('image_height', models.PositiveSmallIntegerField(blank=True, default=100, editable=False, null=True)),
                ('image_width', models.PositiveSmallIntegerField(blank=True, default=100, editable=False, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
